on:
  push:
    branches:
      - "master"


jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    environment:
      name: "Dev"
      url: ${{ vars.DEPLOY_API_URL }}
    defaults:
      run:
        working-directory: "games"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: "23.6"
          cache-dependency-path: "games/yarn.lock"
      - name: "Install dependencies"
        run: "yarn install --frozen-lockfile"
      - name: "Build"
        run: "yarn run build"
      - name: "Deploy cover images"
        run: |
          aws s3 sync ./assets/ "s3://$DO_SPACES_BUCKET/assets/" \
            --endpoint-url "https://$DO_SPACES_REGION.digitaloceanspaces.com" \
            --acl public-read \
            --delete
        env:
          DO_SPACES_BUCKET: ${{ vars.DO_SPACES_BUCKET }}
          DO_SPACES_REGION: ${{ vars.DO_SPACES_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET }}
          AWS_DEFAULT_REGION: "us-east-1"
      - name: "Deploy"
        run: "yarn run diff && yarn run deploy"
        env:
          DEPLOY_API_URL: ${{ vars.DEPLOY_API_URL }}
          DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
